#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clear-font
Version  : 1
Release  : 15
URL      : http://localhost/cgit/projects/clear-font/snapshot/clear-font-1.tar.bz2
Source0  : http://localhost/cgit/projects/clear-font/snapshot/clear-font-1.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: clear-font-data = %{version}-%{release}
Requires: clear-font-license = %{version}-%{release}
BuildRequires : font-util-dev
BuildRequires : mkfontdir-bin
BuildRequires : mkfontscale-bin
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(xorg-macros)

%description
No detailed description available

%package data
Summary: data components for the clear-font package.
Group: Data

%description data
data components for the clear-font package.


%package license
Summary: license components for the clear-font package.
Group: Default

%description license
license components for the clear-font package.


%prep
%setup -q -n clear-font-1
cd %{_builddir}/clear-font-1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604084340
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604084340
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/clear-font
cp %{_builddir}/clear-font-1/LICENSE-2.0.txt %{buildroot}/usr/share/package-licenses/clear-font/2b8b815229aa8a61e483fb4ba0588b8b6c491890
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/defaults/fonts/conf.avail/42-clear.conf
/usr/share/defaults/fonts/conf.d/42-clear.conf
/usr/share/fonts/X11/TTF/ClearSans-Bold.ttf
/usr/share/fonts/X11/TTF/ClearSans-BoldItalic.ttf
/usr/share/fonts/X11/TTF/ClearSans-Italic.ttf
/usr/share/fonts/X11/TTF/ClearSans-Light.ttf
/usr/share/fonts/X11/TTF/ClearSans-Medium.ttf
/usr/share/fonts/X11/TTF/ClearSans-MediumItalic.ttf
/usr/share/fonts/X11/TTF/ClearSans-Regular.ttf
/usr/share/fonts/X11/TTF/ClearSans-Thin.ttf
/usr/share/fonts/X11/TTF/fonts.dir
/usr/share/fonts/X11/TTF/fonts.scale

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/clear-font/2b8b815229aa8a61e483fb4ba0588b8b6c491890
