#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clear-font
Version  : 1
Release  : 11
URL      : http://localhost/cgit/projects/clear-font/snapshot/clear-font-1.tar.bz2
Source0  : http://localhost/cgit/projects/clear-font/snapshot/clear-font-1.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: clear-font-data
BuildRequires : font-util-dev
BuildRequires : mkfontdir-bin
BuildRequires : mkfontscale-bin
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(xorg-macros)

%description
No detailed description available

%package data
Summary: data components for the clear-font package.
Group: Data

%description data
data components for the clear-font package.


%prep
%setup -q -n clear-font-1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510692269
%reconfigure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1510692269
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/defaults/fonts/conf.avail/42-clear.conf
/usr/share/defaults/fonts/conf.d/42-clear.conf
/usr/share/fonts/X11/TTF/ClearSans-Bold.ttf
/usr/share/fonts/X11/TTF/ClearSans-BoldItalic.ttf
/usr/share/fonts/X11/TTF/ClearSans-Italic.ttf
/usr/share/fonts/X11/TTF/ClearSans-Light.ttf
/usr/share/fonts/X11/TTF/ClearSans-Medium.ttf
/usr/share/fonts/X11/TTF/ClearSans-MediumItalic.ttf
/usr/share/fonts/X11/TTF/ClearSans-Regular.ttf
/usr/share/fonts/X11/TTF/ClearSans-Thin.ttf
/usr/share/fonts/X11/TTF/fonts.dir
/usr/share/fonts/X11/TTF/fonts.scale
